### PR TITLE
fixed help

### PR DESCRIPTION
**Pull request by odavid**
The space was causing hubot help not to show these commands.

### CODE REVIEW

**Comment by jmcshane** [comment]
@odavid do you want contributor access? Given the work you've done here, I'm fine if you want to merge these yourself

**Comment by odavid** [comment]
Sure. I hope I won't need to merge more (:
Thanks anyway.
I would be glad if you can publish a version in npm registry, so we can install the package from there without using git url.

Best,
Ohad

**Comment by jmcshane** [comment]
ill publish right now

**Comment by jmcshane** [comment]
0.2.0 is published

**Comment by odavid** [comment]
Thank you! I am in the middle of establishing a bot for CICD process. I might find more bugs/enhancements during that time and will be glad to contribute.
Best,
Ohad

**Pull request merged**
